name: td-merging
channels:
  - defaults
dependencies:
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - openssl=1.1.1o
  - pip=21.2.4
  - python=3.7.2
  - setuptools=61.2.0
  - sqlite=3.38.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - pip:
    - absl-py==1.0.0
    - astunparse==1.6.3
    - cached-property==1.5.2
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - flatbuffers==2.0
    - gast==0.5.3
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.46.1
    - h5py==3.6.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - markdown==3.3.7
    - numpy==1.21.6
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - protobuf==3.20.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - six==1.16.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-io-gcs-filesystem==0.25.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - zipp==3.8.0
prefix: C:\Users\birk\anaconda3\envs\td-merging
